### ISSUE TITLE
Full 2020 Season Schedule Not Displaying

### ISSUE THREAD

**Issue by philipbolin98** [vishaalagartha/basketball_reference_scraper#25] opened 2020-10-27 01:37 UTC
When I use the function get_schedule(2020, playoffs=False), it returns the schedule from the season opener through 2019-10-31 but no games afterward. This seems to be the only season in which this is the case.

Thanks!

**Comment by vishaalagartha** [comment] 2020-10-27 20:11
This was caused by the strange season schedule, but should be fixed now in v1.0.19. Thanks for bringing it to my attention!

**Closed by vishaalagartha** 2020-10-27 20:11 UTC

**Comment by philipbolin98** [comment] 2020-10-28 05:24
Thanks for the quick update! I figured it was because of the weird covid schedule. However it still seems that the function isnt returning the games that were played in March and July. Thanks again!

**Comment by vishaalagartha** [comment] 2020-10-29 00:25
No worries! Let me know if you run into any other issues or can think of any enhancements.
