### ISSUE TITLE
Player Game Logs Pandas Index numbering is incorrect

### ISSUE THREAD

**Issue by Jorge-S** [vishaalagartha/basketball_reference_scraper#10] opened 2020-02-24 23:27 UTC
Recreation:
pg = get_game_logs('Pau Gasol', '2010-01-12', '2010-01-20', playoffs=False)
pg.loc[18:22,:] # return index of Pau's 18-22nd game for the season

Expectation:
Code should output the 4 games on 2009-12-06, 2009-12-09, 2009-12-11, and 2009-12-12 numbered as games 18,19,20,21 (offset by one because of 0-indexing) as seen here.
![Bbref Expectation](https://user-images.githubusercontent.com/25993638/75200063-c26b1380-5732-11ea-8fbf-3813ea179851.PNG)

Reality:
Running the code above has those 4 games numbered as 18, 19, 21, 22. It appears that your program correctly skips the line that BBref uses as the header but still increments the index.

**Comment by vishaalagartha** [comment] 2020-02-25 17:37
Duplicate of #9

**Closed by vishaalagartha** 2020-02-25 17:37 UTC
